<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\EmergencyService;

class EmergencyServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $services = [
            // ── Nationwide Hotlines ──
            [
                'name' => 'Tourist Police (شرطة السياحة)',
                'type' => 'hotline',
                'phone' => '126',
                'address' => 'Nationwide / سرايا شرطة السياحة',
                'city' => 'All',
                'latitude' => null,
                'longitude' => null,
                'details' => 'Available 24/7. Speaks English and other languages for tourist assistance and security reporting.',
                'status' => 'approved',
            ],
            [
                'name' => 'Ambulance Service (الإسعاف المصري)',
                'type' => 'hotline',
                'phone' => '123',
                'address' => 'Nationwide / الإسعاف',
                'city' => 'All',
                'latitude' => null,
                'longitude' => null,
                'details' => 'Available 24/7 for urgent medical emergencies and transportation to the nearest hospital.',
                'status' => 'approved',
            ],
            [
                'name' => 'Fire Department (المطافئ)',
                'type' => 'hotline',
                'phone' => '180',
                'address' => 'Nationwide / الحماية المدنية',
                'city' => 'All',
                'latitude' => null,
                'longitude' => null,
                'details' => 'Available 24/7 for firefighting and civil defense emergency response.',
                'status' => 'approved',
            ],
            [
                'name' => 'Traffic Police (شرطة المرور)',
                'type' => 'hotline',
                'phone' => '128',
                'address' => 'Nationwide / المرور',
                'city' => 'All',
                'latitude' => null,
                'longitude' => null,
                'details' => 'Available 24/7 for road accidents, roadside assistance, and traffic queries.',
                'status' => 'approved',
            ],

            // ── Cairo Services ──
            [
                'name' => 'El Salam International Hospital (مستشفى السلام الدولي)',
                'type' => 'hospital',
                'phone' => '19885',
                'address' => 'Corniche El Nile, Maadi, Cairo',
                'city' => 'Cairo',
                'latitude' => 29.976722,
                'longitude' => 31.248389,
                'details' => 'Private hospital offering 24/7 emergency care, trauma services, and highly qualified English-speaking staff.',
                'status' => 'approved',
            ],
            [
                'name' => 'Anglo-American Hospital (المستشفى الأنجلو أمريكي)',
                'type' => 'hospital',
                'phone' => '+20227356162',
                'address' => 'Hadika Street, Gezira, Zamalek, Cairo',
                'city' => 'Cairo',
                'latitude' => 30.045889,
                'longitude' => 31.223806,
                'details' => 'Historic private hospital located next to the Cairo Tower, popular among expats and tourists.',
                'status' => 'approved',
            ],
            [
                'name' => 'El Ezaby Pharmacy - 24/7 Zamalek (صيدلية العزبي)',
                'type' => 'pharmacy',
                'phone' => '19600',
                'address' => 'El-Shagarah Street, Zamalek, Cairo',
                'city' => 'Cairo',
                'latitude' => 30.0575,
                'longitude' => 31.2222,
                'details' => 'Open 24 hours. Full stock of international medicines and home delivery available via hotline 19600.',
                'status' => 'approved',
            ],
            [
                'name' => 'Embassy of the United States (سفارة الولايات المتحدة)',
                'type' => 'embassy',
                'phone' => '+20227973300',
                'address' => '5 Tawfik Diab Street, Garden City, Cairo',
                'city' => 'Cairo',
                'latitude' => 30.038167,
                'longitude' => 31.233861,
                'details' => 'Consular services for US citizens in Egypt. Open Sun-Thu. Emergency hotline available after hours.',
                'status' => 'approved',
            ],
            [
                'name' => 'Embassy of the United Kingdom (السفارة البريطانية)',
                'type' => 'embassy',
                'phone' => '+20227916000',
                'address' => '7 Ahmed Ragheb Street, Garden City, Cairo',
                'city' => 'Cairo',
                'latitude' => 30.036917,
                'longitude' => 31.232361,
                'details' => 'Consular services for British citizens. Open Sun-Thu. Emergency consular assistance available 24/7.',
                'status' => 'approved',
            ],

            // ── Giza Services ──
            [
                'name' => 'Dar Al Fouad Hospital Giza (مستشفى دار الفؤاد)',
                'type' => 'hospital',
                'phone' => '16370',
                'address' => 'Touristic Zone, 6th of October City, Giza',
                'city' => 'Giza',
                'latitude' => 29.993639,
                'longitude' => 30.963472,
                'details' => 'Joint Commission International (JCI) accredited hospital specialized in cardiac care, chest diseases, and critical care.',
                'status' => 'approved',
            ],
            [
                'name' => 'Misr Pharmacies - Giza (صيدليات مصر)',
                'type' => 'pharmacy',
                'phone' => '19110',
                'address' => 'El Haram Street, Giza',
                'city' => 'Giza',
                'latitude' => 30.0051,
                'longitude' => 31.1895,
                'details' => 'Open 24 hours. Located near the Pyramids area, provides standard prescriptions and cosmetics.',
                'status' => 'approved',
            ],
            [
                'name' => 'French Consulate General Giza (القنصلية العامة الفرنسية بالجيزة)',
                'type' => 'embassy',
                'phone' => '+20235671800',
                'address' => '7 El Fadl Street, Giza',
                'city' => 'Giza',
                'latitude' => 30.0131,
                'longitude' => 31.2089,
                'details' => 'Provides consular support, emergency protection, and assistance for French nationals visiting or residing in Giza.',
                'status' => 'approved',
            ],

            // ── Alexandria Services ──
            [
                'name' => 'German Hospital Alexandria (المستشفى الألماني بالإسكندرية)',
                'type' => 'hospital',
                'phone' => '+2035441544',
                'address' => '56 Abdel Latif El-Sofani Street, Sidi Gaber, Alexandria',
                'city' => 'Alexandria',
                'latitude' => 31.2222,
                'longitude' => 29.9444,
                'details' => 'Highly regarded private medical center offering complete emergency services and bilingual staff.',
                'status' => 'approved',
            ],
            [
                'name' => 'El Ezaby Pharmacy Alexandria (صيدلية العزبي الكورنيش)',
                'type' => 'pharmacy',
                'phone' => '19600',
                'address' => 'Corniche Road, Saba Pasha, Alexandria',
                'city' => 'Alexandria',
                'latitude' => 31.2415,
                'longitude' => 29.9678,
                'details' => 'Open 24/7. Located on the main Corniche road for easy tourist access.',
                'status' => 'approved',
            ],
            [
                'name' => 'Italian Consulate General Alexandria (القنصلية العامة الإيطالية بالإسكندرية)',
                'type' => 'embassy',
                'phone' => '+2034870085',
                'address' => '25 Midan Saad Zaghloul, Raml Station, Alexandria',
                'city' => 'Alexandria',
                'latitude' => 31.2008,
                'longitude' => 29.8992,
                'details' => 'Consular services and emergency support for Italian and EU citizens in Alexandria.',
                'status' => 'approved',
            ],

            // ── Luxor Services ──
            [
                'name' => 'Luxor International Hospital (مستشفى الأقصر الدولي)',
                'type' => 'hospital',
                'phone' => '+20952387192',
                'address' => 'Televizyon Street, Luxor',
                'city' => 'Luxor',
                'latitude' => 25.6833,
                'longitude' => 32.6333,
                'details' => 'The largest medical facility in Luxor equipped for tourist emergency cases and critical surgery.',
                'status' => 'approved',
            ],
            [
                'name' => 'Cleopatra Pharmacy Luxor (صيدلية كليوباترا)',
                'type' => 'pharmacy',
                'phone' => '+20952270000',
                'address' => 'El-Mahatta Square, Luxor Center',
                'city' => 'Luxor',
                'latitude' => 25.6985,
                'longitude' => 32.6421,
                'details' => 'Open 24/7. Conveniently located near the main train station. Speaks English.',
                'status' => 'approved',
            ],
            [
                'name' => 'Luxor Tourist Police & Diplomatic Protection (شرطة السياحة وحماية البعثات بالأقصر)',
                'type' => 'embassy',
                'phone' => '+20952372401',
                'address' => 'Midan Al-Mahatta, Luxor',
                'city' => 'Luxor',
                'latitude' => 25.6991,
                'longitude' => 32.6428,
                'details' => 'Coordination hub for foreign citizens and diplomatic assistance in Upper Egypt. Works in association with local consulates.',
                'status' => 'approved',
            ],

            // ── Aswan Services ──
            [
                'name' => 'Aswan University Hospital (مستشفى أسوان الجامعي)',
                'type' => 'hospital',
                'phone' => '+20972304620',
                'address' => 'Corniche El Nile, Aswan',
                'city' => 'Aswan',
                'latitude' => 24.0889,
                'longitude' => 32.8997,
                'details' => 'Major referral hospital in Aswan offering trauma care and emergency surgery services.',
                'status' => 'approved',
            ],
            [
                'name' => 'Khalil Pharmacy Aswan (صيدلية خليل بأسوان)',
                'type' => 'pharmacy',
                'phone' => '19661',
                'address' => 'El-Sadat Street, Aswan Center',
                'city' => 'Aswan',
                'latitude' => 24.0833,
                'longitude' => 32.8950,
                'details' => '24/7 pharmacy offering prescription fulfillment, tourist medical supplies, and English-speaking pharmacists.',
                'status' => 'approved',
            ],
            [
                'name' => 'Aswan Tourist Protection & Consulate Service (مكتب حماية السياح والخدمات القنصلية بأسوان)',
                'type' => 'embassy',
                'phone' => '+20972315300',
                'address' => 'Abtal El-Tahrir Street, Aswan',
                'city' => 'Aswan',
                'latitude' => 24.0911,
                'longitude' => 32.8989,
                'details' => 'Emergency and consular liaison service desk dedicated to foreign tourists visiting Aswan and Abu Simbel.',
                'status' => 'approved',
            ],

            // ── Sharm El-Sheikh Services ──
            [
                'name' => 'Sharm El-Sheikh International Hospital (مستشفى شرم الشيخ الدولي)',
                'type' => 'hospital',
                'phone' => '+20693660894',
                'address' => 'El-Salam Street, Sharm El-Sheikh',
                'city' => 'Sharm El-Sheikh',
                'latitude' => 27.9158,
                'longitude' => 34.3294,
                'details' => 'State-of-the-art government-run international hospital specifically built for tourists, offering hyperbaric decompression chambers for divers.',
                'status' => 'approved',
            ],
            [
                'name' => 'El Ezaby Pharmacy Naama Bay (صيدلية العزبي نعمة باي)',
                'type' => 'pharmacy',
                'phone' => '19600',
                'address' => 'Naama Bay Promenade, Sharm El-Sheikh',
                'city' => 'Sharm El-Sheikh',
                'latitude' => 27.9135,
                'longitude' => 34.3255,
                'details' => 'Open 24/7. Located in the heart of Naama Bay. International brands and medicines available.',
                'status' => 'approved',
            ],
            [
                'name' => 'German Honorary Consulate Sharm El-Sheikh (القنصلية الفخرية الألمانية بشرم الشيخ)',
                'type' => 'embassy',
                'phone' => '+20693600900',
                'address' => 'Sutton Heights, Hadaba, Sharm El-Sheikh',
                'city' => 'Sharm El-Sheikh',
                'latitude' => 27.8633,
                'longitude' => 34.3012,
                'details' => 'Provides consular assistance, passport emergencies, and administrative support for German and EU citizens in South Sinai.',
                'status' => 'approved',
            ],

            // ── Hurghada Services ──
            [
                'name' => 'El Gouna Hospital (مستشفى الجونة)',
                'type' => 'hospital',
                'phone' => '+20653580011',
                'address' => 'El Gouna, Hurghada',
                'city' => 'Hurghada',
                'latitude' => 27.3956,
                'longitude' => 33.6783,
                'details' => 'High-quality private hospital located in El Gouna with specialized diving medicine and emergency translation services.',
                'status' => 'approved',
            ],
            [
                'name' => 'El Ezaby Pharmacy Hurghada (صيدلية العزبي الغردقة)',
                'type' => 'pharmacy',
                'phone' => '19600',
                'address' => 'Sheraton Road, Hurghada',
                'city' => 'Hurghada',
                'latitude' => 27.2185,
                'longitude' => 33.8421,
                'details' => 'Open 24/7. Delivers to all resorts along Sheraton Road and Mamsha. Speaks English and Russian.',
                'status' => 'approved',
            ],
            [
                'name' => 'Russian Consulate General in Hurghada (القنصلية العامة لروسيا الاتحادية بالغردقة)',
                'type' => 'embassy',
                'phone' => '+20653465759',
                'address' => 'End of Interdistrict Street, Hurghada',
                'city' => 'Hurghada',
                'latitude' => 27.1645,
                'longitude' => 33.8214,
                'details' => 'Full consular services for Russian nationals. Emergency hotline available for citizens in distress.',
                'status' => 'approved',
            ],

            // ── Marsa Alam Services ──
            [
                'name' => 'Port Ghalib Hospital (مستشفى بورت غالب)',
                'type' => 'hospital',
                'phone' => '+20653545611',
                'address' => 'Port Ghalib Marina, Marsa Alam',
                'city' => 'Marsa Alam',
                'latitude' => 25.5342,
                'longitude' => 34.6322,
                'details' => 'Modern emergency medical facility with decompression chamber services for diving accidents.',
                'status' => 'approved',
            ],
            [
                'name' => 'Port Ghalib Pharmacy (صيدلية بورت غالب)',
                'type' => 'pharmacy',
                'phone' => '+201099933887',
                'address' => 'Marina Promenade, Marsa Alam',
                'city' => 'Marsa Alam',
                'latitude' => 25.5350,
                'longitude' => 34.6315,
                'details' => 'Open 24/7. Offers major international medical brands, sunscreens, and first aid supplies for tourists.',
                'status' => 'approved',
            ],
            [
                'name' => 'Marsa Alam Foreign Citizens Assistance & Tourist Police (مكتب مساعدة الأجانب وشرطة السياحة بمرسى علم)',
                'type' => 'embassy',
                'phone' => '+20653380020',
                'address' => 'Main Highway, Marsa Alam Center',
                'city' => 'Marsa Alam',
                'latitude' => 25.0754,
                'longitude' => 34.8899,
                'details' => 'Dedicated unit for tourist assistance, lost documents, consular coordination, and local security guidance.',
                'status' => 'approved',
            ],

            // ── Port Said Services ──
            [
                'name' => 'El Naser Hospital Port Said (مستشفى النصر التخصصي ببورسعيد)',
                'type' => 'hospital',
                'phone' => '+20663259100',
                'address' => 'El-Amin Street, Port Said',
                'city' => 'Port Said',
                'latitude' => 31.2585,
                'longitude' => 32.2856,
                'details' => 'A state-of-the-art facility operating under the comprehensive health insurance system, equipped for emergencies.',
                'status' => 'approved',
            ],
            [
                'name' => 'Delmar & Attalla Pharmacy Port Said (صيدلية دلمار وعطا الله)',
                'type' => 'pharmacy',
                'phone' => '19955',
                'address' => 'Tarrahin Street, Port Said Center',
                'city' => 'Port Said',
                'latitude' => 31.2612,
                'longitude' => 32.3005,
                'details' => 'Open 24 hours. Conveniently located near the port, offering standard medications and beauty products.',
                'status' => 'approved',
            ],
            [
                'name' => 'Italian Consular Agency Port Said (الوكالة القنصلية الإيطالية ببورسعيد)',
                'type' => 'embassy',
                'phone' => '+20663220050',
                'address' => 'Gomhouria Street, Port Said',
                'city' => 'Port Said',
                'latitude' => 31.2645,
                'longitude' => 32.3032,
                'details' => 'Provides essential consular and emergency support for Italian and EU citizens visiting the Suez Canal region.',
                'status' => 'approved',
            ],

            // ── Fayoum Services ──
            [
                'name' => 'Fayoum University Hospital (مستشفى الفيوم الجامعي)',
                'type' => 'hospital',
                'phone' => '+20842148000',
                'address' => 'El-Gamaa Street, Fayoum City',
                'city' => 'Fayoum',
                'latitude' => 29.3195,
                'longitude' => 30.8415,
                'details' => 'The largest educational and emergency medical center in the Fayoum Governorate.',
                'status' => 'approved',
            ],
            [
                'name' => 'El Ezaby Pharmacy Fayoum (صيدلية العزبي بالفيوم)',
                'type' => 'pharmacy',
                'phone' => '19600',
                'address' => 'El-Horreya Street, Fayoum Center',
                'city' => 'Fayoum',
                'latitude' => 29.3090,
                'longitude' => 30.8440,
                'details' => 'Open 24 hours. Offers local home delivery and coordinates with medical centers for prescription drugs.',
                'status' => 'approved',
            ],
            [
                'name' => 'Fayoum Tourist Police & Diplomatic Desk (مكتب شرطة السياحة والاتصال الدبلوماسي بالفيوم)',
                'type' => 'embassy',
                'phone' => '+20846330050',
                'address' => 'Near Fayoum Governorate HQ, Fayoum',
                'city' => 'Fayoum',
                'latitude' => 29.3081,
                'longitude' => 30.8422,
                'details' => 'Direct assistance bureau helping foreign tourists with translation, emergency consular links, and safety reporting.',
                'status' => 'approved',
            ],
        ];

        foreach ($services as $service) {
            EmergencyService::create($service);
        }
    }
}
